### ISSUE TITLE
Add ability to set custom execution command

### ISSUE THREAD

**Issue by joker-777** [benmelz/haml-lint-intellij-plugin#50]
Hi, I'm trying to get this plugin working in rubymine (latest version) but somehow the errors don't show up. They do show up when running `bundle exec haml-lint` manually though. What can I do to investigate this?

**Comment by benmelz** [comment]
Hello, just to rule it out, have you verified that the inspection is enabled in your settings?

If so, some further diagnostic information would help, including what OS you are running (+ if it is windows, are using WSL?) as well as any relevant logs (I would locate your IDE log via `Help` -> `Show Log` -> search that text file for "HamlLint").

You can post it here if you're comfortable with that, or send an email to `ben@melz.me`.

**Comment by joker-777** [comment]
@benmelz Wow, thanks for your swift response. I use archlinux and yes, it is enabled. I forgot to mention that I use docker. The rubocop inspection works though. I will send you the log file via email.

![Screenshot_20231023_220926](https://github.com/benmelz/haml-lint-intellij-plugin/assets/378859/cfc19cce-7342-47ff-8e8e-46ed51bacbad)
![Screenshot_20231023_222421](https://github.com/benmelz/haml-lint-intellij-plugin/assets/378859/b0bff115-4cbf-403b-98a7-3b7faaed73d1)
![Screenshot_20231023_222243](https://github.com/benmelz/haml-lint-intellij-plugin/assets/378859/a2295df7-cd9a-4f3d-9bd8-7a389e060f7f)

**Comment by benmelz** [comment]
Ah yes, it is most definitely docker that is throwing a wrench in things - the plugin is currently hardcoded to execute using  `bundle exec haml-lint`.

I will look into adding support for you, most likely by allowing customization of the execution command.

**Comment by benmelz** [comment]
^ The new version hopefully be available on the marketplace tomorrow, 2023-23-10 (depending on how fast jetbrains people review/approve it). I've added the aforementioned customization option to the inspection profile settings.

Based on your screenshot, the configuration for your project should look like...

![Screenshot 2023-10-23 at 6 15 28 PM](https://github.com/benmelz/haml-lint-intellij-plugin/assets/8195530/cfc7c040-4af7-4d42-a620-947e6ee55bad)

Thanks for the report! (and do let me know if you still have problems)

**Comment by joker-777** [comment]
@benmelz Thanks a lot for fixing this so quickly. If it works like this, perfect. I wonder though if you should use the same approach as the Rubcop integration does and run haml-lint from the project SDK. The selected SDK can also use docker.

**Comment by benmelz** [comment]
> I wonder though if you should use the same approach as the Rubcop integration does and run haml-lint from the project SDK

Yes this would be the most ideal setup (which I initially attempted to set up when I first wrote this plugin). Unfortunately the ruby/rubocop plugins are closed source and the IntelliJ API documentation is... sparse, so admittedly I haven't the slightest idea how I would go about doing it.

<hr />

Another possible hiccup just occurred to me as well regarding docker integration - the plugin works by taking the current file contents of the editor, [writing it to a tempfile](https://github.com/benmelz/haml-lint-intellij-plugin/blob/main/src/main/kotlin/me/benmelz/jetbrains/plugins/hamllint/HamlLintTarget.kt) and running haml-lint against that. This is necessary because
- the IDE "lazily" saves files (often only when focus is lost), so we must use the in-memory versions of the files, or else the plugin would be _super_ slow
- `haml-lint` does not provide a `--stdin` option like `rubocop` does - it _must_ be run against a real file

As such the tempfile might not be available since you're executing in a docker container. A possible fix though could be locally mounting part of your temp dir inside the container. For me on macOS, the files get written to `/private/var/folders/f0`, (determined by the java property `java.io.tmpdir`, it seems), so perhaps `-v /private/var/folders/f0:/private/var/folders:f0` as a docker option would work as a hack.

<hr />

Now for a long term fix, I have contributed to `haml-lint` myself in the past and I've been toying with the idea of submitting a patch to add such a `--stdin` flag for performance reasons. The idea of "files only" is pretty central to the gem though, so I might need to find some down time to do the refactoring. If it comes to fruition I'll let you know.

**Comment by joker-777** [comment]
Yes, I also tried to find the code but couldn't. Have ask JetBrains for guidance? I'm sure they are interested in well-working plugins. 

Thanks for the explanation. Fortunately, my `/tmp` folder is already mapped.

I just tried the new version and at first it found a lot of errors. Using the following command made it work in the end.

`docker compose exec -e HAML_LINT_RUBOCOP_CONF=/app/.rubocop.yml web bundle exec haml-lint`

**Comment by benmelz** [comment]
Awesome, glad we got something working

> Have ask JetBrains for guidance? I'm sure they are interested in well-working plugins.

Admittedly I have not 😅, but since I now know other people use the plugin, perhaps I will try to reach out to someone on their team this weekend.

**Comment by joker-777** [comment]
@benmelz Maybe it is also worth having a look at other linter plugins, e.g.

https://github.com/JetBrains/intellij-plugins/tree/master/tslint
https://github.com/idok/sass-lint-plugin

BTW, thanks a lot for maintaining it!!!!
